### ISSUE TITLE
WordPress Code Standards through PHPCS

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/edit-screen-shortcode-lister#1]
### Background 

We'd like to use this plugin on WordPress VIP Go. The existing shortcode lister plugin does exactly what we're looking to do, but it produces a few errors and warnings about sanitizing and escaping when we run it through PHP Code Sniffer.

Since the change set required to meet the WordPress code standards is relatively small, and we can contribute to the plugin ourselves, let's do it.

As a reminder the PHPCS report from when we initially researched the plugin is here: https://github.com/wpcomvip/shopcatalog/issues/393

Since this plugin doesn't have its own PHPCS config yet, use can use your global install of PHPCS or PHPCBF like this...

`phpcs --standard=WordPress,WordPress-VIP-Go`

### Tasks

- [x] Use PHPCS to test the existing plugin code against the WordPress and WordPress-VIP-Go standards.
- [x] Use PHPCBF for the small stuff like spacing and tabs.
- [x] Add [phpDocumentor](https://docs.phpdoc.org/latest/) style comments where requested
- [x] Escape output where requested
- [x] Sanitize input where requested
- [ ] Create nonces in forms
- [ ] Verify nonces during form processing

### Using Forks

- Make a pull request to master on this fork, and we'll review it.
- Then we'll make a pull request to the original repository.

### References

- https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/
- https://developer.wordpress.org/themes/theme-security/using-nonces/
- https://developer.wordpress.org/reference/functions/wp_create_nonce/
- https://developer.wordpress.org/reference/functions/wp_verify_nonce/
- https://developer.wordpress.org/reference/functions/wp_nonce_field/
